# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea4d59a141523c273895b03cd0d8bbdc70826cd64d668885a136b27ecee0b0a73a199c3f43486c549a003735c7addbbf69f0bce0a737cb15b2f6dcd2c8a1c53d

test:
  secret_key_base: 859c70a9db134dd2ba7573fa89e02bf2082b308a727a412871d2dae603456cdb023826d51d2e2a2d9befcf5f91a6a7f83ea75812d41d2d1c6c6537cfe7f94ef2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
